sudo: required

language: generic

services:
  - docker

env:
  global:
    - DOCKER_BUILD_OPTION="--force-rm --no-cache --pull"
  
before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

jobs:
  include:
    - stage: build docker image
      if: type != cron
      env: BASEIMG=centos7_dev TAG=latest
      script:
        - docker build -t gwangmin/base:$TAG -f dockerfiles/base --build-arg BASEIMG=$BASEIMG $DOCKER_BUILD_OPTION .
        - docker push gwangmin/base:$TAG

    - stage: build docker image
      if: type != cron
      env: BASEIMG=ubuntu_dev:bionic TAG=ubuntu
      script:
        - docker build -t gwangmin/base:$TAG -f dockerfiles/base --build-arg BASEIMG=$BASEIMG $DOCKER_BUILD_OPTION .
        - docker push gwangmin/base:$TAG

    - stage: build basic docker image
      if: type = cron
      env: DOCKERFILE_NAME=centos7_dev
      script:
        - docker build -t gwangmin/${DOCKERFILE_NAME}:latest -f dockerfiles/$DOCKERFILE_NAME $DOCKER_BUILD_OPTION .
        - docker push gwangmin/${DOCKERFILE_NAME}:latest

    - stage: build basic docker image
      if: type = cron
      env: 
        - DOCKERFILE_NAME=ubuntu_dev
        - TAG=bionic
      script:
        - docker build -t gwangmin/ubuntu_dev:${TAG} -f dockerfiles/$DOCKERFILE_NAME --build-arg VERSION=${TAG} $DOCKER_BUILD_OPTION .
        - docker push gwangmin/ubuntu_dev:${TAG}

    - stage: build basic docker image
      if: type = cron
      env: 
        - DOCKERFILE_NAME=ubuntu_dev
        - TAG=xenial
      script:
        - docker build -t gwangmin/ubuntu_dev:${TAG} -f dockerfiles/$DOCKERFILE_NAME --build-arg VERSION=${TAG} $DOCKER_BUILD_OPTION .
        - docker push gwangmin/ubuntu_dev:${TAG}

    - stage: build basic docker image
      if: type = cron
      env: DOCKERFILE_NAME=jenkins_did
      script:
        - docker build -t gwangmin/${DOCKERFILE_NAME}:latest -f dockerfiles/$DOCKERFILE_NAME $DOCKER_BUILD_OPTION .
        - docker push gwangmin/${DOCKERFILE_NAME}:latest

    - stage: build basic docker image
      if: type = cron
      env: DOCKERFILE_NAME=jenkins_slave_did
      script:
        - docker build -t gwangmin/${DOCKERFILE_NAME}:latest -f dockerfiles/$DOCKERFILE_NAME $DOCKER_BUILD_OPTION .
        - docker push gwangmin/${DOCKERFILE_NAME}:latest

notifications:
  slack:
    secure: SU91a1fKEwOf65eJjk2+hhh3XtGb/sf5Ka+4AAa9OTBDsYyNMKQnUmpHM/A4a0kKxz64UbzH8Vbj4HflekTCdCBkyuIaC093Krhc1QdrvkTJS2jz1WsBuwB8ZkwOhT3r7mN8F97pqJrB4kAF4V5hThU2hAFLtemDoGFd4VwLkdksYeLuxlerVK2UhIkHQ2i8cnxUDWiIel4r5qsjvKIUXSn2HT9MnkxooUHTp52QU2uF/y6buMOhS7YQmiOoHpvhVJsuZJjY54gXfhe3tXYFfZE2+8/FYO5qjKJIr/UXJe+tuOEB6VH7rQNpA3TeribvGF72dvlp2qqVY/4O+Lz9+2DqvDO/RH2PzKyDsRvlQKRd6tnLW6hPPa+PxQs4Qwi9Vz7wCqfsISZDVKLzQjXIFGpEPVzpevr2By1UO3wuMdqTPatJ0mTFtHODDsfmGYRs0qzJ+lGIhJ+k/WsFasigjHdLmFTEhZ5FyQWXOP8kpDtJLdl0z/X1S0XFPvXXmUWRrnXp4aP1xwZhKhJfVxDtjfcsaS2RR+qBkLc3eccJKn4XDd9pJezteGQXer5rR7m87HMXw+m/Qnl3LZ6NWhhaHnMJ7tal0allXpt0qofRx/BGbRJjve/3FxL2+sPbeFSqNZ2MTlnYyX8hTEPO/3T0gfhJ4NryIrrx+hF89onEGsI=
