sudo: required

language: generic

services:
  - docker

env:
  global:
    - DOCKER_BUILD_OPTION="--force-rm --no-cache --pull"
  matrix:
    - BASEIMG=centos_7_dev TAG=latest
    - BASEIMG=centos_7_gcc_7 TAG=gcc7
  
before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - docker build -t gwangmin/base:$TAG -f dockerfiles/base --build-arg BASEIMG=$BASEIMG $DOCKER_BUILD_OPTION .
  - docker push gwangmin/base:$TAG
