sudo: required

services:
  - docker

env:
  - DOCKER_BUILD_OPTION="--force-rm --no-cache --pull"
  
before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

install: true

jobs:
  include:
    - stage: build docker image
      script: 
        - docker build -t gwangmin/base:latest -f dockerfiles/base --build-arg BASEIMG=centos_7_dev $DOCKER_BUILD_OPTION .
        - docker push gwangmin/base:latest
      script: 
        - docker build -t gwangmin/base:gcc7 -f dockerfiles/base --build-arg BASEIMG=centos_7_dev_gcc_7 $DOCKER_BUILD_OPTION .
        - docker push gwangmin/base:gcc7
